extends:
  - 'serverless-stack'
  - standard
rules:
  space-before-function-paren: off
overrides:
  - files:
      - 'test/**/*.test.ts'
      - 'jest-test-setup.ts'
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'

