charcot:
  sqs:
    order:
      queue:
        url:
          https://sqs.us-east-1.amazonaws.com/045387143127/dev-charcot-cerebrum-image-order-queue
  dynamodb:
    order:
      table:
        name:
          dev-charcot-cerebrum-image-order
    image:
      metadata:
        table:
          name:
            dev-charcot-cerebrum-image-metadata
  s3:
    zip:
      bucket:
        name:
          cerebrum-image-zip-dev
  ses:
    from:
      email:
        no-reply@dev.mountsinaicharcot.org