charcot:
  dynamodb:
    order:
      table:
        name:
          prod-charcot-cerebrum-image-order
    image:
      metadata:
        table:
          name:
            prod-charcot-cerebrum-image-metadata
  s3:
    zip:
      bucket:
        name:
          cerebrum-image-zip
  ses:
    from:
      email:
        no-reply@mountsinaicharcot.org