charcot:
  dynamodb:
    order:
      table:
        name:
          debug-charcot-cerebrum-image-order
    image:
      metadata:
        table:
          name:
            debug-charcot-cerebrum-image-metadata
  s3:
    zip:
      bucket:
        name:
          cerebrum-image-zip-debug
  ses:
    from:
      email:
        no-reply@debug.mountsinaicharcot.org
  profile:
    name:
      odp:
        mssm